server:
  persistentVolume:
    enabled: false

alertmanager:
  enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: otelcol
        static_configs:
          - targets:
              - workshop-release-otelcol.default.svc.cluster.local:9464
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090
