apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    # image tags are relative; to specify an image repo (e.g. GCR), you
    # must provide a "default repo" using one of the methods described
    # here:
    # https://skaffold.dev/docs/concepts/#image-repository-handling
    - image: adservice
      docker:
        dockerfile: src/adservice/Dockerfile
    - image: cartservice
      docker:
        dockerfile: src/cartservice/Dockerfile
    - image: checkoutservice
      docker:
        dockerfile: src/checkoutservice/Dockerfile
    - image: currencyservice
      context: src/currencyservice
      docker:
        dockerfile: src/currencyservice/Dockerfile
        buildArgs:
          GRPC_VERSION: 1.46.0
          OPENTELEMETRY_VERSION: 1.5.0
    - image: emailservice
      context: src/emailservice
      docker:
        dockerfile: src/emailservice/Dockerfile
    - image: frontend
      docker:
        dockerfile: src/frontend/Dockerfile
    - image: frontendproxy
      docker:
        dockerfile: src/frontendproxy/Dockerfile
    - image: loadgenerator
      docker:
        dockerfile: src/loadgenerator/Dockerfile
    - image: paymentservice
      docker:
        dockerfile: src/paymentservice/Dockerfile
    - image: productcatalogservice
      docker:
        dockerfile: src/productcatalogservice/Dockerfile
    - image: recommendationservice
      docker:
        dockerfile: src/recommendationservice/Dockerfile
    - image: shippingservice
      docker:
        dockerfile: src/shippingservice/Dockerfile
  tagPolicy:
    inputDigest: {}
  local:
    useBuildkit: false
    concurrency: 1
    tryImportMissing: true
deploy:
  helm:
    releases:
      - name: workshop-release
        chartPath: chart
        recreatePods: false
        skipBuildDependencies: false
        artifactOverrides:
          components.cartService.image: cartservice
          components.recommendationService.image: recommendationservice
          components.shippingService.image: shippingservice
          components.paymentService.image: paymentservice
          components.productCatalogService.image: productcatalogservice
          components.loadgenerator.image: loadgenerator
          components.currencyService.image: currencyservice
          components.checkoutService.image: checkoutservice
          components.adService.image: adservice
          components.emailService.image: emailservice
          components.frontend.image: frontend
          components.frontendproxy.image: frontendproxy
        useHelmSecrets: false
        wait: false
