apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    # image tags are relative; to specify an image repo (e.g. GCR), you
    # must provide a "default repo" using one of the methods described
    # here:
    # https://skaffold.dev/docs/concepts/#image-repository-handling
    - image: adservice
      docker:
        dockerfile: src/adservice/Dockerfile
    - image: cartservice
      docker:
        dockerfile: src/cartservice/Dockerfile
    - image: checkoutservice
      docker:
        dockerfile: src/checkoutservice/Dockerfile
    - image: currencyservice
      docker:
        dockerfile: src/currencyservice/Dockerfile
    - image: emailservice
      context: src/emailservice
      docker:
        dockerfile: src/emailservice/Dockerfile
    - image: frontend
      docker:
        dockerfile: src/frontend/Dockerfile
    - image: loadgenerator
      docker:
        dockerfile: src/loadgenerator/Dockerfile
    - image: paymentservice
      docker:
        dockerfile: src/paymentservice/Dockerfile
    - image: productcatalogservice
      docker:
        dockerfile: src/productcatalogservice/Dockerfile
    - image: recommendationservice
      docker:
        dockerfile: src/recommendationservice/Dockerfile
    - image: shippingservice
      docker:
        dockerfile: src/shippingservice/Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    useBuildkit: false
deploy:
  kubectl:
    manifests:
      - ./kubernetes-manifests/**.yaml
