apiVersion: v1
kind: Service
metadata:
  name: qcon-workshop-grafana-external
  namespace: default
spec:
  ports:
  - name: service
    port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: prom-grafana
    app.kubernetes.io/name: grafana
  type: LoadBalancer