name: "Release"

on:
  push:
    branches:
     - main

jobs:
  build_and_push_images:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: "${{ github.event.release.tag_name }}"
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache skaffold image builds & config
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/
          key: fixed

      - uses: azure/setup-helm@v3

      - name: "test ecr login"
        run: |
          aws ecr get-login-password --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

      - name: Run Skaffold pipeline
        uses: hiberbee/github-action-skaffold@1.19.0
        with:
          command: run
          repository: ${{ secrets.AWS_ECR_REPO }}
          kube-context: 'arn:aws:eks:$AWS_REGION:${{ secrets.AWS_ACCOUNT }}:cluster/${{ secrets.AWS_EKS_CLUSTER_NAME }}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
